name: Database Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/mysql/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  migrate:
    name: Run database migrations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install golang-migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.0/migrate.linux-amd64.tar.gz | tar xvz
          mkdir -p bin
          mv migrate bin/migrate
          chmod +x bin/migrate
          
      - name: Run database migrations
        run: |
          # Only run migrations up, never down
          DB_USER="${{ secrets.DB_USER }}"
          DB_PASS="${{ secrets.DB_PASS }}"
          DB_HOST="${{ secrets.DB_HOST }}"
          DB_PORT="${{ secrets.DB_PORT || '3306' }}"
          DB_NAME="${{ secrets.DB_NAME }}"
          
          # Construct DSN from environment variables or use the provided one
          if [ -n "${{ secrets.DB_MIGRATE_DSN }}" ]; then
            DB_DSN="${{ secrets.DB_MIGRATE_DSN }}"
          else
            DB_DSN="mysql://${DB_USER}:${DB_PASS}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?parseTime=true"
          fi
          
          echo "Running migrations with constructed DSN"
          ./bin/migrate -path migrations/mysql -database "${DB_DSN}" up